 // This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "commons": {
    "actions": {
      "chat": "Chat",
      "clear-all": "Clear All",
      "clear-confirmation": "Click again to clear",
      "global-traits": {
        "desc": "The prompt will be append into the query when you skid your homework to personalize the response.",
        "placeholder": "You're a smart assistant that helps the user with the homework.",
        "submit-btn": "Submit",
        "title": "Edit Global Traits",
        "trigger": "Global Traits Editor"
      },
      "processing": "Processing...",
      "scan": "Let's Skid",
      "settings": "Settings",
      "title": "Add Images"
    },
    "chat-page": {
      "actions": {
        "back": "Back to Scanner",
        "delete-chat": "Delete Chat",
        "new-chat": "New Chat"
      },
      "composer": {
        "placeholder": "Ask a question or paste a problem...",
        "send": "Send",
        "sending": "Sending..."
      },
      "conversation": {
        "empty": "Select a chat or start a new one to begin.",
        "empty-title": "No conversation selected"
      },
      "errors": {
        "missing-key": "{{provider}} needs an API key before you can chat.",
        "no-model": "Please set a model name before chatting.",
        "no-source": "Please enable at least one source with an API key in Settings.",
        "send-failed": "Failed to send message: {{error}}",
        "unsupported": "The selected model does not support conversations."
      },
      "history": {
        "empty": "No chats yet. Start a conversation.",
        "title": "History",
        "unknown-source": "Unknown provider",
        "untitled": "New chat"
      },
      "source": {
        "empty": "No models found.",
        "model": "Model name",
        "model-placeholder": "gpt-4.1-mini or models/gemini-2.5-pro",
        "search": "Search model...",
        "section": "Model",
        "select": {
          "placeholder": "Select a model"
        }
      },
      "subtitle": "Discuss problems with your configured models.",
      "title": "SkidHomework Chat"
    },
    "improve-dialog": {
      "description": "Generate a more detailed solution using the current solution and your prompt.",
      "placeholder": "Make it more detailed...",
      "submit": "Submit",
      "title": "Improve the Solution",
      "toasts": {
        "failed": {
          "description": "Something went wrong: {{error}}",
          "parse": "Failed to parse response, see the developer tools for more details.",
          "title": "Failed to improve your solution"
        },
        "no-key": {
          "description": "Please set an API key for {{provider}} in Settings to continue.",
          "title": "You're almost there"
        },
        "no-source": {
          "description": "Enable at least one AI provider in Settings before improving a solution.",
          "title": "No AI sources"
        },
        "processing": {
          "description": "Improving your solution with AI...Please wait for a while...",
          "title": "Processing"
        }
      },
      "trigger": "Improve the Solution"
    },
    "init-page": {
      "features": {
        "camera": "Snap homework and get step-by-step help.",
        "setup": "Fast setup — paste your Gemini API key and go.",
        "telemetry": "No telemetry or spammy calls. Just the Gemini API."
      },
      "footer": {
        "notice": "Licensed under GPLv3, created by cubewhy.",
        "source": "Source Code"
      },
      "form": {
        "advanced": {
          "base-url-helper": "Leave blank to use the default endpoint for {{provider}}.",
          "base-url-label": "API Base URL (optional)",
          "base-url-placeholder": "Default endpoint for {{provider}}",
          "title": "Advanced"
        },
        "api-hint": "Get an API key at <link>Google AI Studio</link>.",
        "api-hint-openai": "Get an API key at <link>OpenAI Dashboard</link>.",
        "key-placeholder": "{{provider}} API Key",
        "provider": {
          "label": "AI provider"
        },
        "storage-note": "We store your key locally using encrypted browser storage and never send it to our servers.",
        "submit": "Get My Time Back!"
      },
      "headline": {
        "highlight": "Welcome to SkidHomework",
        "subtitle": "Escape the homework grind."
      },
      "intro": "Prefer Khan Academy–style self-study but still get stuck with endless assignments? SkidHomework runs locally, respects your privacy, and helps you focus on learning instead of busywork.",
      "preview": {
        "hints": "Hints",
        "ocr": "OCR",
        "steps": "Steps",
        "title": "Homework Camera"
      },
      "tagline": "Local • Private • Free"
    },
    "preview": {
      "drag-tip": "You can drag your files to this panel.",
      "drag-tip-mobile": "Tap a card to zoom in. Swipe left or right to review everything.",
      "drop-cancel": "Drag here to cancel",
      "file-type": {
        "pdf": "PDF",
        "unknown": "Unknown type"
      },
      "image-alt": "Homework preview",
      "no-files": "No files yet. Upload or take a photo to begin.",
      "remove-aria": "Remove image",
      "title": "Preview"
    },
    "problem-list": {
      "item-label": "Problem {{index}}"
    },
    "scan-page": {
      "donate-btn": "Donate now",
      "errors": {
        "missing-key": "Missing API key for {{provider}}.",
        "parsing-failed": "Failed to parse the AI response.",
        "processing-failed": {
          "answer": "Please check the console for errors and try again.",
          "explanation": "{{error}}",
          "problem": "Processing failed after multiple retries."
        }
      },
      "footer": {
        "license": "Licensed under GPL-3.0.",
        "slogan": "Students' lives matter",
        "source": "Source code"
      },
      "mobile": {
        "empty": "Add a photo or PDF to get started.",
        "hint-pdf": "Enable a Gemini source in Settings to allow PDF uploads.",
        "hint-ready": "You're ready to scan. Tap “Let's Skid” when you're set.",
        "status": "{{count}} file ready",
        "status_plural": "{{count}} files ready",
        "tabs": {
          "capture": "Capture",
          "preview": "Review"
        }
      },
      "tip": "We never upload without your action.",
      "title": "Scan your homework",
      "toasts": {
        "all-processed": {
          "description": "There are no pending or failed images to scan.",
          "title": "All images processed"
        },
        "done": {
          "description": "Your homework has been processed.",
          "title": "All done!"
        },
        "error": {
          "description": "Something went wrong during the process. Please check the console.",
          "title": "An unexpected error occurred"
        },
        "no-key": {
          "description": "Please set an API key for {{provider}} in Settings.",
          "title": "You're almost there"
        },
        "no-model": {
          "description": "Please choose a model for {{provider}} in Settings before scanning.",
          "title": "Model required"
        },
        "no-source": {
          "description": "Enable at least one AI provider with an API key in Settings before scanning.",
          "title": "No AI sources configured"
        },
        "pdf-blocked": {
          "description": "Enable a Gemini source to process PDF files.",
          "title": "PDF uploads disabled"
        },
        "heic-convert-failed": {
          "description": "Export the image as JPG/PNG and try again.",
          "title": "Couldn't convert HEIC photo"
        },
        "working": {
          "description": "Sending {{count}} file(s) to your AI sources...",
          "title": "Working..."
        }
      }
    },
    "settings-page": {
      "advanced": {
        "custom-base-url": {
          "helper": "Leave blank to use the default endpoint for {{provider}}.",
          "placeholder": "https://example.com/v1",
          "title": "Custom API base URL"
        },
        "desc": "Extras that affect uploads and the interface.",
        "image-post-processing": {
          "binarizing": "Enable binarizing",
          "title": "Image Post-processing"
        },
        "title": "Advanced Settings",
        "ui": {
          "show-donate-btn": "Show donate button",
          "title": "UI"
        }
      },
      "api-credentials": {
        "applied": "API key saved.",
        "desc": "Store API keys locally for each AI provider. They never leave your browser.",
        "label": "API Key",
        "name": {
          "label": "Source name",
          "placeholder": "Friendly name shown in the app"
        },
        "placeholder": "Enter your {{provider}} API key",
        "title": "API Credentials"
      },
      "appearance": {
        "desc": "Choose how SkidHomework looks and which language it uses.",
        "language": {
          "desc": "Switch the interface language.",
          "label": "Language",
          "options": {
            "en": "English",
            "zh": "中文"
          }
        },
        "theme": {
          "desc": "Use the system preference or pick a fixed mode.",
          "label": "Theme",
          "options": {
            "dark": "Dark",
            "light": "Light",
            "system": "System"
          }
        },
        "title": "Appearance & Language"
      },
      "back": "Back",
      "clear-input": "Clear",
      "heading": "SkidHomework Settings",
      "model": {
        "desc": "Choose or type the model name used for requests.",
        "fetch": {
          "error": "Failed to fetch models for {{provider}}. Check your API key or base URL."
        },
        "manual": {
          "desc": "Enter a model name manually if it is not listed.",
          "placeholder": "Model identifier",
          "title": "Custom model"
        },
        "refresh": "Refresh models",
        "sel": {
          "empty": "No models found.",
          "none": "No model selected",
          "search": "Search model...",
          "unknown": "Unknown model ({{name}})"
        },
        "title": "Model Configuration"
      },
      "openai": {
        "poll-interval": {
          "desc": "How long to wait between response status checks.",
          "title": "Polling interval (ms)"
        },
        "poll-timeout": {
          "desc": "Maximum time to wait for a response before failing.",
          "title": "Polling timeout (ms)"
        }
      },
      "reset": "Reset",
      "shortcuts": {
        "actions": {
          "camera": {
            "description": "Launches the device camera to capture homework.",
            "label": "Take photo"
          },
          "clearAll": {
            "description": "Removes every uploaded item and solution.",
            "label": "Clear all"
          },
          "open-global-traits-editor": {
            "description": "Open the editor dialog to edit global traits (prompt)",
            "label": "Open Global Traits Editor"
          },
          "openChat": {
            "description": "Jump straight to the chat workspace.",
            "label": "Open chat"
          },
          "openSettings": {
            "description": "Opens this settings page from anywhere in the app.",
            "label": "Open settings"
          },
          "startScan": {
            "description": "Sends all pending items to your AI sources.",
            "label": "Start scan"
          },
          "upload": {
            "description": "Opens the file picker for selecting images or PDFs.",
            "label": "Upload files"
          }
        },
        "clear": "Clear",
        "desc": "Customize the keys used for common actions. Leave blank to disable a shortcut.",
        "manual": {
          "invalid": "Enter a valid shortcut using modifier keys plus a key.",
          "placeholder": "Type shortcut (e.g. Ctrl+1)"
        },
        "recording": "Press keys…",
        "reset": "Reset to defaults",
        "title": "Keyboard shortcuts",
        "unassigned": "Unassigned"
      },
      "sources": {
        "active": {
          "badge": "Active",
          "label": "Active source"
        },
        "add": {
          "cancel": "Cancel",
          "confirm": "Add source",
          "label": "Add AI source",
          "name": "Display name (optional)",
          "name-placeholder": "e.g. Classroom Gemini",
          "provider": "Provider",
          "success": "Added {{name}}.",
          "title": "Add AI source"
        },
        "desc": "Manage enabled AI providers and choose which one to configure.",
        "enabled": {
          "label": "Enabled sources",
          "toggle": "Enabled"
        },
        "make-active": "Set active",
        "option": "{{name}} • {{provider}}",
        "providers": {
          "gemini": "Gemini",
          "openai": "OpenAI"
        },
        "remove": {
          "error": "Keep at least one AI source.",
          "label": "Remove source",
          "success": "Removed {{name}}."
        },
        "title": "AI Sources"
      },
      "thinking": {
        "budget": "Thinking budget",
        "desc": "Adjust advanced thinking parameters for supported providers.",
        "title": "Thinking Settings",
        "tokens-unit": "tokens"
      },
      "traits": {
        "desc": "Define the assistant's persona or extra instructions.",
        "placeholder": "e.g., You are a helpful assistant that speaks in a friendly and professional tone.",
        "title": "System Prompt (Traits)"
      }
    },
    "solution-viewer": {
      "answer": "Answer",
      "chat": {
        "button": "Chat about this",
        "context": {
          "answer": "Answer:\n{{answer}}",
          "explanation": "Explanation:\n{{explanation}}",
          "intro": "The learner is reviewing the following work:",
          "problem": "Problem:\n{{problem}}"
        },
        "default-title": "Homework chat",
        "fallback": {
          "answer": "Answer not available.",
          "explanation": "Explanation not available.",
          "problem": "Problem not available."
        },
        "no-problem": {
          "description": "Choose a problem before starting a chat.",
          "title": "Select a problem first"
        },
        "no-source": {
          "description": "Configure an AI source with an API key in Settings to chat.",
          "title": "No model available"
        },
        "prefill": {
          "intro": "I'd like help understanding this problem.",
          "outro": "Can you walk me through it step by step?"
        }
      },
      "copy": {
        "button": "Copy answer",
        "failed": {
          "description": "Please copy manually.",
          "title": "Copy failed"
        },
        "success": {
          "description": "Answer copied to clipboard.",
          "title": "Copied"
        }
      },
      "explanation": "Explanation",
      "navigation": {
        "next-image": "Image ⟶",
        "next-problem": "Next",
        "prev-image": "⟵ Image",
        "prev-problem": "Prev"
      },
      "open-preview": "open preview",
      "progress": {
        "prefix": "Problem",
        "suffix": "of {{total}}"
      },
      "source-image": "Source image:"
    },
    "solutions": {
      "analyzing": "Analyzing... extracting problems and solutions from your images.",
      "export": {
        "answer-label": "Answer",
        "button": "Export as Markdown",
        "document-title": "Homework Solutions",
        "empty": {
          "description": "Run a scan and wait for results before exporting.",
          "title": "Nothing to export"
        },
        "error": {
          "description": "Something went wrong while creating the markdown file.",
          "title": "Export failed"
        },
        "explanation-label": "Explanation",
        "filename-prefix": "homework-solutions",
        "page-heading": "Page {{index}} · {{name}}",
        "placeholders": {
          "answer": "_No answer provided._",
          "explanation": "_No explanation provided._",
          "problem": "_No problem content provided._"
        },
        "problem-heading": "Problem {{index}}",
        "problem-label": "Problem",
        "success": {
          "description": "Your solutions file is ready.",
          "title": "Markdown downloaded"
        }
      },
      "focus-region-aria": "Solutions keyboard focus region (Tab/Shift+Tab for problems, Space/Shift+Space for images)",
      "gesture-hint": "Swipe left or right to switch problems.",
      "idle": "No solutions yet. Add images and click \"Let's Skid\" to see results here.",
      "photo-label": "Photo {{index}} • {{source}}",
      "status": {
        "failed": "Failed to process this image. Please try again.",
        "pending": "Processing in progress...",
        "stream": "Reasoning...",
        "success": "No problems were detected for this image.",
        "success-with-provider": "Solved by {{provider}}."
      },
      "streaming": {
        "placeholder": "AI is thinking...",
        "title": "AI Output"
      },
      "tabs": {
        "fallback": "File {{index}}"
      },
      "title": "Solutions",
      "toggle-preview": "Toggle Preview"
    },
    "sources": {
      "camera": "Camera",
      "upload": "Upload"
    },
    "upload-area": {
      "camera-help-aria": "Camera help",
      "camera-tip": {
        "close": "Got it",
        "intro": "The <takePhoto>Take Photo</takePhoto> button uses the browser's native camera picker (<capture>capture=\"environment\"</capture>). On phones, it opens the camera directly. On desktops, it usually falls back to the file chooser.",
        "tips": ["Prefer natural light and avoid glare.", "Fill the frame with the problem. Keep text sharp.", "One question per shot yields better recognition."],
        "title": "Taking photos on different devices"
      },
      "pdf-disabled": "PDF uploads are available only when a Gemini source is enabled.",
      "take-photo": "Take Photo",
      "upload": "Upload Files",
      "upload-tip": "Images are supported. PDFs require an active Gemini source."
    },
    "uploads-info": {
      "selected": "Selected"
    }
  }
}

export default Resources;
